const MODEL = 'openai/gpt-oss-20b'
const API_BASE_URL = 'https://api.groq.com/openai/v1'

export const useAI = () => {
	const userStore = useUserStore()
	const { error: showError } = useToast()

	const generateTextWithAI = async (prompt: string): Promise<string> => {
		const apiKey = userStore.getUserAiApiKey

		if (!apiKey) {
			throw new Error('API key not found')
		}

		try {
			const response = await fetch(`${API_BASE_URL}/chat/completions`, {
				method: 'POST',
				headers: {
					Authorization: `Bearer ${apiKey}`,
					'Content-Type': 'application/json',
				},
				body: JSON.stringify({
					model: MODEL,
					messages: [
						{
							role: 'user',
							content: prompt,
						},
					],
				}),
			})

			if (!response.ok) {
				throw new Error(`API request failed: ${response.statusText}`)
			}

			const data = await response.json()

			return data?.choices[0]?.message?.content ?? ''
		} catch (err) {
			console.error('AI generation error:', err)
			showError('Failed to connect to AI service')
			throw err
		}
	}

	const generateExplanation = async (params: {
		setName: string
		setDescription: string
		question: string
		answers: string[]
		selectedAnswer: string
	}): Promise<string> => {
		const prompt = `
			Explain why the answer is correct or incorrect in context of flashcard quiz named "${params.setName}" 
			and described as "${params.setDescription}". 
			Question was "${params.question}" and answers were "${params.answers.join(', ')}". 
			User picked answer "${params.selectedAnswer}". 
			Use same language as the language of the flashcard quiz question and answers (probably English or Polish)! 
			Do not repeat the question or answers in your explanation!
			Try to use some examples to explain the answer!
			Do it in easy to understand language! Your goal is to help the user understand the topic better!
			Format your response as clean HTML. Use:
			- <strong> for bold text
			- <em> for emphasis
			- <p> for paragraphs
			- <ul> and <li> for lists
			- <table>, <thead>, <tbody>, <tr>, <th>, <td> for tables
			- <code> for inline code
			- <pre><code> for code blocks
			- use some empty lines inside to make it more readable

			Do not use markdown syntax. Return only HTML. Be like a teacher explaining the answer to a student, wanted to help them understand the topic better.
		`

		return await generateTextWithAI(prompt)
	}

	const generateFlashcard = async (params: {
		topic: string
		setName: string
		setDescription: string
	}): Promise<{ question: string; answers: string[] }> => {
		const prompt = `Generate ABCD question and 4 answers (1 correct and 3 incorrect, answers must have random size, once shorter, once longer) about "${params.topic}" in context of flashcard quiz named "${params.setName}" and described as "${params.setDescription}". Try to think like a teacher or recruiter, trying to verify if the student/interviewer knows the topic. Return only JSON object with properties "question" and "answers", where answers have just text items, and first one is correct, no other text in your response. Example question and answers for example topic "France": {"question": "What is the capital of France?", "answers": ["Paris", "London", "Berlin", "Madrid"]}`

		const content = await generateTextWithAI(prompt)
		const parsed = JSON.parse(content || '{}')

		return {
			question: parsed.question || '',
			answers: parsed.answers || [],
		}
	}

	const generateFlashcardTopics = async (params: {
		topic: string
		amount: number
	}): Promise<string[]> => {
		const prompt = `Generate ${params.amount} flashcard topic-items to learn about: "${params.topic}". Try to think like a teacher or recruiter, trying to verify if the student/interviewer knows the topic. Try to pick all important topics, in context of the given area. Return only the quoted items in a comma separated array, no other text. Items should be in same language as the given topic. Items should be just short words or phrases, not sentences, not questions (questions will be generated by AI later from these items).`

		const content = await generateTextWithAI(prompt)
		const parsed = JSON.parse(`[${content}]`)

		return Array.isArray(parsed) ? parsed : []
	}

	return {
		generateExplanation,
		generateFlashcard,
		generateFlashcardTopics,
	}
}
